language: python
sudo: required
dist: xenial
python: "3.7"
install:
  - pip install git+https://github.com/jamespfennell/transiter
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  - make test
after_success:
  - coveralls
