language: python
sudo: required
dist: xenial
python: "3.7"
install:
  - git clone git://github.com/jamespfennell/transiter.git
  - pip install -e transiter
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  - make test
after_success:
  - coveralls
