name: New York City Subway


requirements:
  packages:
    - transiter_nycsubway
  settings:
    - mta_api_key


feeds:

  gtfsstatic:
    http:
      url: 'http://web.mta.info/developers/data/nyct/subway/google_transit.zip'
    parser:
      built_in: GTFS_STATIC
    required_for_install: true
    auto_update:
      enabled: false

  DirectionRules:
    http:
      url: 'http://web.mta.info/developers/data/nyct/subway/Stations.csv'
    parser:
      custom: 'transiter_nycsubway.stationscsvparser:parse'
    required_for_install: true
    auto_update:
      enabled: false

  gtfsrealtime-alerts:
    http:
      url: "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/camsys%2Fsubway-alerts"
      headers:
        X-API-KEY: "{{ mta_api_key }}"
    parser:
      built_in: "transiter_ny_mta:AlertsParser"
    auto_update:
      period: {{ update_periodicity or '5' }} seconds

  {%
for id_, mta_url_postfix in (
    ("7", "-7"),
    ("123456", ""),
    ("ACE", "-ace"),
    ("BDFM", "-bdfm"),
    ("G", "-g"),
    ("JZ", "-jz"),
    ("L", "-l"),
    ("NQRW", "-nqrw"),
    ("SIR", "-si")
)
%}
  {{ id_ }}:
    http:
      url: "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs{{ mta_url_postfix }}"
      headers:
        X-API-KEY: "{{ mta_api_key }}"
    parser:
      custom: 'transiter_nycsubway.gtfsrealtimeparser:parse'
    auto_update:
      period: {{ update_periodicity or '5' }} seconds
{% endfor %}


service_maps:

  any_time:
    source: SCHEDULE
    threshold: 0.05
    use_for_stops_in_route: true

  weekday_day:
    source: SCHEDULE
    conditions:
      weekday: true
      starts_later_than: 7
      ends_earlier_than: 19
    threshold: 0.1
    use_for_routes_at_stop: true

  weekday_night:
    source: SCHEDULE
    conditions:
      weekday: true
      starts_later_than: 0
      ends_earlier_than: 6
    threshold: 0.1

  weekend:
    source: SCHEDULE
    conditions:
      weekend: true
      starts_later_than: 7
      ends_earlier_than: 19
    threshold: 0.1

  realtime:
    source: REALTIME
    use_for_stops_in_route: true
    use_for_routes_at_stop: true
