name: PATH Train

feeds:

  gtfsstatic:
    http:
      url: "http://data.trilliumtransit.com/gtfs/path-nj-us/path-nj-us.zip"
    parser:
      built_in: GTFS_STATIC
    required_for_install: true
    auto_update:
      enabled: false

  gtfsrealtime-trips:
    http:
      url: "https://path.transitdata.nyc/gtfsrt"
    parser:
      built_in: GTFS_REALTIME
    auto_update:
      period: {{ update_periodicity or '300' }} seconds
