name: New York City Subway


requirements:
  packages:
    - transiter_nycsubway
  settings:
    - mta_api_key


feeds:

  gtfsstatic:
    http:
      url: 'http://web.mta.info/developers/data/nyct/subway/google_transit.zip'
    parser:
      built_in: GTFS_STATIC
    required_for_install: true
    auto_update:
      enabled: false

  ServiceStatus:
    http:
      url: 'http://web.mta.info/status/ServiceStatusSubway.xml'
    parser:
      custom: 'transiter_nycsubway.servicestatusxmlparser:parse'
    auto_update:
      period: 5 seconds

  7:
    http:
      url: 'https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-7'
      headers:
        X-API-KEY: "{mta_api_key}"
    parser:
      custom: 'transiter_nycsubway.gtfsrealtimeparser:parse'
    auto_update:
      period: 5 seconds

  123456:
    http:
      url: 'https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs'
      headers:
        X-API-KEY: "{mta_api_key}"
    parser:
      custom: 'transiter_nycsubway.gtfsrealtimeparser:parse'
    auto_update:
      period: 5 seconds

  ACE:
    http:
      url: 'https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-ace'
      headers:
        X-API-KEY: "{mta_api_key}"
    parser:
      custom: 'transiter_nycsubway.gtfsrealtimeparser:parse'
    auto_update:
      period: 5 seconds

  BDFM:
    http:
      url: 'https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-bdfm'
      headers:
        X-API-KEY: "{mta_api_key}"
    parser:
      custom: 'transiter_nycsubway.gtfsrealtimeparser:parse'
    auto_update:
      period: 5 seconds

  G:
    http:
      url: 'https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-g'
      headers:
        X-API-KEY: "{mta_api_key}"
    parser:
      custom: 'transiter_nycsubway.gtfsrealtimeparser:parse'
    auto_update:
      period: 5 seconds

  JZ:
    http:
      url: 'https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-jz'
      headers:
        X-API-KEY: "{mta_api_key}"
    parser:
      custom: 'transiter_nycsubway.gtfsrealtimeparser:parse'
    auto_update:
      period: 5 seconds

  L:
    http:
      url: 'https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-l'
      headers:
        X-API-KEY: "{mta_api_key}"
    parser:
      custom: 'transiter_nycsubway.gtfsrealtimeparser:parse'
    auto_update:
      period: 5 seconds

  NQRW:
    http:
      url: 'https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-nqrw'
      headers:
        X-API-KEY: "{mta_api_key}"
    parser:
      custom: 'transiter_nycsubway.gtfsrealtimeparser:parse'
    auto_update:
      period: 5 seconds

  SIR:
    http:
      url: 'https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-si'
      headers:
        X-API-KEY: "{mta_api_key}"
    parser:
      custom: 'transiter_nycsubway.gtfsrealtimeparser:parse'
    auto_update:
      period: 5 seconds


service_maps:

  any_time:
    source: SCHEDULE
    threshold: 0.05
    use_for_stops_in_route: true

  weekday_day:
    source: SCHEDULE
    #conditions:
    #  weekday: true
    #  starts_later_than: 7
    #  ends_earlier_than: 19
    threshold: 0.1
    use_for_routes_at_stop: true

  weekday_night:
    source: SCHEDULE
    #conditions:
    #  weekday: true
    #  starts_later_than: 0
    #  ends_earlier_than: 6
    threshold: 0.1

  weekend:
    source: SCHEDULE
    # conditions:
    #  weekend: true
    #  starts_later_than: 7
    #  ends_earlier_than: 19
    threshold: 0.1

  realtime:
    source: REALTIME
    use_for_stops_in_route: true
    use_for_routes_at_stop: true


direction_rules_files:
  - http:
      url: https://raw.githubusercontent.com/jamespfennell/transiter-nycsubway/master/config/nyc_subway_direction_name_rules_with_track.csv
  - http:
      url: https://raw.githubusercontent.com/jamespfennell/transiter-nycsubway/master/config/nyc_subway_direction_name_rules_basic.csv


